### ISSUE TITLE
dat-fox breaks the URL global object

### ISSUE THREAD

**Issue by terrygonguet** [sammacbeth/dat-fox#34]
This extension replaces `window.URL` with its own constructor and thus makes its static methods unavailable (`URL.createObjectURL()` and `URL.revokeObjectURL()`). I haven't looked into fixing it yet but it should be trivial.

**Comment by jeremyredhead** [comment]
It [replaces window.URL](../blob/66a91d0c474a25b40591b472110738352d40306d/window/window.js) with npm package [url-parse](https://www.npmjs.com/package/url-parse).
I suspect the offending line may be removed entirely, but I haven't tested this.
(For reference, Beaker Browser appears to have the normal URL constructor)

Also, the fact that DatArchive is exposed & URL overridden on every single http page could potentially be used for fingerprinting I think. So there should probably be an option to change that behavior.

**Comment by sammacbeth** [comment]
Yes. This was required due to inconsistent parsing of unknown URLs by Firefox's URL implementation ([bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1374505)). Since [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1559356) was fixed `dat` is whitelisted as a known protocol, so `URL` behaves correctly. That means, going forward, this polyfill could be removed.
